namespace:
  name: prod

image:
  repository: omstrat/techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%

containerPort: 3111

service:
    port: 7111
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
    type: ClusterIP

livenessProbe:
  httpGet:
    path: /healthz
    port: {{ .Values.containerPort }}

readinessProbe:
    httpGet:
        path: /healthz
        port: {{ .Values.containerPort }}
