namespace:
  name: sandbox

image:
  repository: omstrat/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%

containerPort: 3111

service:
    port: 4111
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
    type: ClusterIP

livenessProbe:
  httpGet:
    path: /healthz
    port: {{ .Values.containerPort }}

readinessProbe:
    httpGet:
        path: /healthz
        port: {{ .Values.containerPort }}
